### ISSUE TITLE
[新功能] 左侧收银信息栏，增加显示实时扫码的商品信息。

### ISSUE THREAD

**Issue by chuan9964** [chuan9964/SupermarketCashierManagementSystem#11]
先把前端弄好，写一个静态的例子上去，有效果了在写后端。

![image](https://github.com/chuan9964/SupermarketCashierManagementSystem/assets/150600079/8df30e95-73ae-41db-91a5-268f4136af3a)

![image](https://github.com/chuan9964/SupermarketCashierManagementSystem/assets/150600079/8dee2154-fd8b-444c-87f9-af91b8aca6cd)

**Comment by wangXinping** [comment]
![image](https://github.com/chuan9964/SupermarketCashierManagementSystem/assets/145627437/2a6e7939-8dca-49a6-afa8-d3a95ffb9b00)
扫码或手动输入商品编号后，左侧自动显示商品详情信息（图片未显示，因为路径还未改好）
