### ISSUE TITLE
[bug] 收银台界面的账单结算功能，输入金额 != 账单金额时，结算会出现问题。

### ISSUE THREAD

**Issue by chuan9964** [chuan9964/SupermarketCashierManagementSystem#13]
收银台界面。结算时，如果输入金额 != 账单金额。点击提交后会没有反应(但是后台生成了账单。)

![D17081E6-DC18-4df3-BCEF-179A0B4BB38A](https://github.com/chuan9964/SupermarketCashierManagementSystem/assets/150600079/0e02dc78-7c62-45d5-b578-ba0b4f5c96e1)

![0638C10A-CADA-40e5-89AD-BE9464C63855](https://github.com/chuan9964/SupermarketCashierManagementSystem/assets/150600079/e3fd2e51-8878-4ce0-9c7b-d01c6f2d7b16)

**Comment by wangXinping** [comment]
![image](https://github.com/chuan9964/SupermarketCashierManagementSystem/assets/145627437/c8b082ee-fffc-4178-8f29-f3632226ecb4)
当实付大于等于应付时，会清空结算清单
