### ISSUE TITLE
[bug] 订单管理，打开详情后显示的页面不正确。

### ISSUE THREAD

**Issue by chuan9964** [chuan9964/SupermarketCashierManagementSystem#15]
订单管理，打开详情后显示的页面不正确。怎么会显示【修改商品】呢？应该显示订单的详情信息（只做显示就可以）。
![image](https://github.com/chuan9964/SupermarketCashierManagementSystem/assets/150600079/c00cdc7d-54de-4d8c-8d81-389dca8808a1)
点开【详情】后：
![image](https://github.com/chuan9964/SupermarketCashierManagementSystem/assets/150600079/d84171f5-6983-4018-8ec5-fa5d9b8ff848)

**Comment by wangXinping** [comment]
将修改商品页面更新为订单详情页面（只显示订单详情）
![image](https://github.com/chuan9964/SupermarketCashierManagementSystem/assets/145627437/09e2c5f2-dbda-4f57-8092-99f4698f441f)

**Comment by chuan9964** [comment]
![image](https://github.com/chuan9964/SupermarketCashierManagementSystem/assets/150600079/0d50cea9-8071-40de-a448-21b9a81ba68e)
