### ISSUE TITLE
[优化] 订单管理页面，状态字段的显示问题。

### ISSUE THREAD

**Issue by chuan9964** [chuan9964/SupermarketCashierManagementSystem#16]
订单管理页面，状态显示改为中文的显示。不应该显示状态值。
![image](https://github.com/chuan9964/SupermarketCashierManagementSystem/assets/150600079/84ca1dc7-7311-4384-8b40-955823163cbd)

**Comment by wangXinping** [comment]
订单管理状态已修改为中文显示
![image](https://github.com/chuan9964/SupermarketCashierManagementSystem/assets/145627437/ec6707ed-1cab-473e-b179-6c5d215f1bd6)
