### ISSUE TITLE
[新功能] 新增【会员卡管理】模块，这个功能的任务量较大。

### ISSUE THREAD

**Issue by chuan9964** [chuan9964/SupermarketCashierManagementSystem#17]
新增【会员卡管理】模块，大致是一个列表，可以新增会员卡信息。
*需要新增数据表 字段大概有：【卡号，余额，姓名，手机号，办卡时间，是否启用】。
*可能会有新文件的新增 比如html文件或js文件。甚至是controller文件。
有点难做，算是一个大任务。
![image](https://github.com/chuan9964/SupermarketCashierManagementSystem/assets/150600079/41729d72-1115-4d49-be59-a8d39b97f558)

**Comment by chuan9964** [comment]
这个要和其他模块的表格等样式一致。

**Comment by wangXinping** [comment]
【会员卡管理】模块的实现
![image](https://github.com/chuan9964/SupermarketCashierManagementSystem/assets/145627437/dcee0c58-5c20-4939-9280-c926bffb9109)
![image](https://github.com/chuan9964/SupermarketCashierManagementSystem/assets/145627437/401fff4a-bd43-4504-932c-1007248d32ef)

**Comment by wangXinping** [comment]
后端权限![image](https://github.com/chuan9964/SupermarketCashierManagementSystem/assets/145627437/2fac785f-9cbf-4a25-8272-c1d0d098b847)前端权限
![image](https://github.com/chuan9964/SupermarketCashierManagementSystem/assets/145627437/e44bf393-e7f3-4ea4-9f90-56609b3b3cf5)
需要在数据库中权限表加入对应的权限字段，前端类型1，后端类型2
![image](https://github.com/chuan9964/SupermarketCashierManagementSystem/assets/145627437/d64a58d4-3363-4ab4-87e6-0d37745897b6)

![image](https://github.com/chuan9964/SupermarketCashierManagementSystem/assets/145627437/88186e22-6db5-4387-b5a2-340186abfcfd)

**Comment by wangXinping** [comment]
可以使用mybatis中自带的mapper接口进行增删改查操作，可以不用自己写SQL语句
![image](https://github.com/chuan9964/SupermarketCashierManagementSystem/assets/145627437/a57dc7aa-066a-4299-9461-2f7b179fb9da)
