### ISSUE TITLE
[bug] 当没有输入任何编号时，点击添加，左侧的商品信息会显示异常

### ISSUE THREAD

**Issue by chuan9964** [chuan9964/SupermarketCashierManagementSystem#18]
当没有输入任何编号时，点击添加，左侧的商品信息窗口，会把所有的商品显示出来。
建议更改非空判断，或者限定查询集合的大小
![image](https://github.com/chuan9964/SupermarketCashierManagementSystem/assets/150600079/2e95397e-43b9-412e-ab7e-2d6f1eaca5ea)

**Comment by wangXinping** [comment]
点击添加时进行非空判断
![image](https://github.com/chuan9964/SupermarketCashierManagementSystem/assets/145627437/8a830a8e-9717-4c2c-bf22-3e80fc8f81f0)
