### ISSUE TITLE
[bug] 解决import com.swetake.util.Qrcode报错

### ISSUE THREAD

**Issue by chuan9964** [chuan9964/SupermarketCashierManagementSystem#2]
解决import com.swetake.util.Qrcode;报错问题
lib 下有jar包可以导入

![157f6dcb5ec24a797be04069c536104](https://github.com/chuan9964/SupermarketCashierManagementSystem/assets/150600079/b0668233-4eb3-4e5f-a61b-53b516501d49)

**Comment by wangXinping** [comment]
右键add as libraries，解压jar包

**Comment by wangXinping** [comment]
![image](https://github.com/chuan9964/SupermarketCashierManagementSystem/assets/145627437/4c1e1c07-6606-4a63-a2e8-774aa06a27fb)
