### ISSUE TITLE
[bug] 页面上时间显示有误，注意时区问题。(不紧急)

### ISSUE THREAD

**Issue by chuan9964** [chuan9964/SupermarketCashierManagementSystem#21]
建议更改为可读性高的格式 xxxx年xx月xx日的，可以在实体类的get()方法里面处理。
![image](https://github.com/chuan9964/SupermarketCashierManagementSystem/assets/150600079/d9bd0584-0478-4e39-90b7-c4a653a673a5)

**Comment by wangXinping** [comment]
![image](https://github.com/chuan9964/SupermarketCashierManagementSystem/assets/145627437/581cb136-65cd-4d65-a60c-14fd7bac6bbb)
已解决

**Comment by wangXinping** [comment]
![image](https://github.com/chuan9964/SupermarketCashierManagementSystem/assets/145627437/9e3571ed-335a-4a9d-9a2c-c4cafbc207ba)
