### ISSUE TITLE
[优化] 正确构建并启动本项目

### ISSUE THREAD

**Issue by chuan9964** [chuan9964/SupermarketCashierManagementSystem#3]
是否启动本项目，请截图。

**Comment by chuan9964** [comment]
测试

**Comment by wangXinping** [comment]
已正确启动项目
![image](https://github.com/chuan9964/SupermarketCashierManagementSystem/assets/145627437/0eb64996-6a7b-46fd-9c61-75df369a7b52)

**Comment by wangXinping** [comment]
已启动本项目
![Uploading image.png…]()
