### ISSUE TITLE
[新功能] 刷卡支付-结算界面刷卡可以触发支付

### ISSUE THREAD

**Issue by chuan9964** [chuan9964/SupermarketCashierManagementSystem#31]
在结算界面，可以刷卡实现支付。
*在支付框弹出的时候，焦点默认加在卡号输入框上了。
实现思路：
![image](https://github.com/chuan9964/SupermarketCashierManagementSystem/assets/150600079/12e4be8c-8826-4dc0-8727-e8731edf61d8)

使用后端的接口，更改isPay的状态。就可以了。（之前已经写过前端监控isPay的事件了）

**Comment by wangXinping** [comment]
利用窗口的隐藏/显示来判断输入框中的值是查询商品还是刷卡支付
![image](https://github.com/chuan9964/SupermarketCashierManagementSystem/assets/145627437/591433e9-c18a-499f-9240-4c9d75360c1b)
若是刷卡支付，调用后端接口，进行更改isPay状态
![image](https://github.com/chuan9964/SupermarketCashierManagementSystem/assets/145627437/2dc3f0c5-5ead-4ce2-914d-f68f186b569a)
