### ISSUE TITLE
[新功能] 短信通知-订单完成后会发送短信通知交易信息。

### ISSUE THREAD

**Issue by chuan9964** [chuan9964/SupermarketCashierManagementSystem#32]
![image](https://github.com/chuan9964/SupermarketCashierManagementSystem/assets/150600079/9d7102fb-510e-4c7a-8d53-f44df09ec387)

**Comment by wangXinping** [comment]
生成一个工具类，订单完成后调用工具类中的方法，进行短信发送功能
![1709627008212](https://github.com/chuan9964/SupermarketCashierManagementSystem/assets/145627437/033942eb-4a26-43d2-8876-3d227b4346e9)
