### ISSUE TITLE
[优化] 隐藏库存管理的二维码绑定窗口

### ISSUE THREAD

**Issue by chuan9964** [chuan9964/SupermarketCashierManagementSystem#5]
隐藏右下角的二维码（注释掉）
![image](https://github.com/chuan9964/SupermarketCashierManagementSystem/assets/150600079/5b597602-6641-4df2-aaa4-06415769bfce)
![image](https://github.com/chuan9964/SupermarketCashierManagementSystem/assets/150600079/d798c494-258c-43e7-889d-eb1af700fa9a)

**Comment by wangXinping** [comment]
代码已注释，已隐藏右下角二维码
![image](https://github.com/chuan9964/SupermarketCashierManagementSystem/assets/145627437/91d14094-0f25-4659-a5fa-5c606a5dccf8)
