### ISSUE TITLE
[新功能] 收银台页面，购物车列表每个商品的名字后面加上小图片

### ISSUE THREAD

**Issue by chuan9964** [chuan9964/SupermarketCashierManagementSystem#8]
收银台页面，购物车列表内，每个商品的名字后面要加上商品的图片（小，最好规定统一的像素）
![image](https://github.com/chuan9964/SupermarketCashierManagementSystem/assets/150600079/f2f030ac-537e-4971-8565-916def8dfc4c)

**Comment by wangXinping** [comment]
结算清单中商品名称后面加商品图片
![image](https://github.com/chuan9964/SupermarketCashierManagementSystem/assets/145627437/7abd5544-e7e8-46de-89c2-ebd9b71a90cc)

**Comment by chuan9964** [comment]
👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍
