### ISSUE TITLE
[优化] 支付方式只保留微信扫码支付和刷卡支付

### ISSUE THREAD

**Issue by chuan9964** [chuan9964/SupermarketCashierManagementSystem#9]
支付方式只保留微信扫码支付和刷卡支付
![image](https://github.com/chuan9964/SupermarketCashierManagementSystem/assets/150600079/80b4e3db-6a39-4b63-946e-7ee40d5f3d3d)

**Comment by wangXinping** [comment]
![image](https://github.com/chuan9964/SupermarketCashierManagementSystem/assets/145627437/435f59b2-3e3d-4933-85f9-b31495d55f51)
